name: nososova
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.4.3
  provider: ^6.0.5
  convert: ^3.1.1
  pointycastle: ^3.7.3
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  get_it: ^7.6.2
  shared_preferences: ^2.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  connectivity_plus: ^4.0.2


dev_dependencies:
  drift_dev: ^2.11.1
  build_runner: ^2.4.6
  flutter_gen: ^5.3.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

