name: nososova
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.4.3
  provider: ^6.0.5
  http: ^1.1.0
  convert: ^3.1.1
  pointycastle: ^3.7.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

