name: nososova
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.4.3
  provider: ^6.0.5
  convert: ^3.1.1
  pointycastle: ^3.7.3
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  get_it: ^7.6.2
  shared_preferences: ^2.2.1
  file_picker: ^5.5.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  connectivity_plus: ^4.0.2


dev_dependencies:
  drift_dev: ^2.11.1
  build_runner: ^2.4.6
  flutter_gen: ^5.3.1
  package_rename: ^1.5.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true

# dart run package_rename
package_rename_config:
  android:
    app_name: NosoSova # (String) The display name of the android app
    package_name: # (String) The package name of the android app
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: NosoSova # (String) The display name of the ios app
    bundle_name: # (String) The bundle name of the ios app
    package_name: # (String) The product bundle identifier of the ios app

  linux:
    app_name: NosoSova # (String) The window title of the linux app
    package_name: # (String) The application id of the linux app
    exe_name: # (String) The executable name (binary name) of the linux app

  macos:
    app_name: NosoSova # (String) The product name of the macos app
    package_name: # (String) The product bundle identifier of the macos app
    copyright_notice: # (String) The product copyright of the macos app


  windows:
    app_name: NosoSova # (String) The window title & software name of the windows app
    organization: NosoCoin # (String) The organization name (company name) of the windows app
    copyright_notice: # (String) The legal copyright of the windows app
    exe_name: NosoSova # (String) The executable name (binary name) of the windows app