name: noso_dart
description: "Implementation of basic cryptographic functions for Noso"
version: 1.0.0
homepage: "https://nosocoin.com/"

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pointycastle: ^3.7.3


flutter: