name: NosoSova Main Workflow

permissions:
  contents: write

defaults:
  run:
    shell: bash

on:

  push:
    branches: [ main, create-ci-cd ]
    tags: [ "*" ]
    paths-ignore: [ "README.md" ]

  pull_request:
    branches: [ main ]

jobs:

  build-linux:
    name: Build Linux (ubuntu-latest)
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false

    steps:
      - name: Install Ubuntu packages
        run: sudo apt install -y ninja-build libgtk-3-dev

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: flutter build linux --release

      - name: List Files
        run: |
          echo "Listing build/linux/x64/release/bundle"
          ls -alF build/linux/x64/release/bundle

      - name: Upload bundle folder
        uses: actions/upload-artifact@v3
        with:
          name: NosoSova-ubuntu-latest-x86_64-bundle
          path: build/linux/x64/release/bundle

  build-windows:
    name: Build Windows (windows-latest)
    runs-on: [windows-latest]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: flutter build windows --release

      - name: List Files
        run: |
          echo "Listing build/windows/x64/release/bundle"
          ls -alF build/windows/x64/release/bundle

      - name: Upload bundle folder
        uses: actions/upload-artifact@v3
        with:
          name: NosoSova-windows-latest-x86_64-bundle
          path: build/windows/x64/release/bundle
