name: NosoSova Main Workflow

permissions:
  contents: write

defaults:
  run:
    shell: bash

on:

  push:
    branches: [ main, create-ci-cd ]
    tags: [ "*" ]
    paths-ignore: [ "README.md" ]

  pull_request:
    branches: [ main ]

jobs:

  build-linux:
    name: Build Linux (ubuntu-latest;flutter 3.16.0)
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false

    steps:
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update -y
          sudo apt install -y ninja-build libgtk-3-dev

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: |
          flutter config --enable-linux-desktop
          flutter build linux --release

      - name: List Files
        run: |
          echo "Listing build/linux/x64/release/bundle"
          ls -alF build/linux/x64/release/bundle

      - name: Upload bundle folder
        uses: actions/upload-artifact@v4
        with:
          name: NosoSova-ubuntu-latest-x86_64-bundle
          path: build/linux/x64/release/bundle

  build-windows:
    name: Build Windows (windows-latest;flutter 3.16.0)
    runs-on: [windows-latest]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      - name: List Files
        run: |
          echo "Listing build/windows/x64/runner/Release"
          ls -alF build/windows/x64/runner/Release

      - name: Upload Release folder
        uses: actions/upload-artifact@v4
        with:
          name: NosoSova-windows-latest-x86_64-release
          path: build/windows/x64/runner/Release

  build-macos:
    name: Build macOS (macos-latest;flutter 3.16.0)
    runs-on: [macos-latest]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --release

      - name: List Files
        run: |
          echo "Listing build/macos/Build/Products/Release/NosoSova.app"
          ls -alF build/macos/Build/Products/Release/NosoSova.app

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: NosoSova-macos-latest-x86_64-NosoSova_app
          path: build/macos/Build/Products/Release/NosoSova.app

  build-android:
    name: Build Android (ubuntu-latest;flutter 3.16.0;Java zulu 17)
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: flutter build apk --release

      - name: List Files
        run: |
          echo "Listing build/app/outputs/apk"
          ls -alF build/app/outputs/apk/release

      - name: Upload apk folder
        uses: actions/upload-artifact@v4
        with:
          name: NosoSova-ubuntu-latest-android-apk
          path: build/app/outputs/apk/release

  build-ios:
    name: Build iOS (macos-latest;flutter 3.16.0)
    runs-on: [macos-latest]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: |
          flutter build ios --release --no-codesign

      - name: List Files
        run: |
          echo "Listing build"
          ls -alF build

#      - name: Upload build folder
#        uses: actions/upload-artifact@v4
#        with:
#          name: NosoSova-macos-latest-ios-build
#          path: build
