name: NosoSova Main Workflow

permissions:
  contents: write

defaults:
  run:
    shell: bash

on:

  push:
    branches: [ main, create-ci-cd ]
    tags: [ "*" ]
    paths-ignore: [ "README.md" ]

  pull_request:
    branches: [ main ]

jobs:

  build-macos:
    name: Build macOS (macos-latest;flutter 3.16.0)
    runs-on: [macos-latest]
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Application
        run: flutter build macos --release

      - name: List Files
        run: |
          echo "Listing build/macos/Build"
          ls -alF build/macos/Build

      #- name: Upload build folder
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: NosoSova-macos-latest-x86_64-build
      #    path: build
